# Generated by Django 4.1.1 on 2022-12-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_numberoffollowers_post_like_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberOfFollowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
